# Generated by Django 5.2.1 on 2025-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.BigIntegerField(blank=True, null=True)),
                ('total_price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('personnel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_teacher', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('has_check', models.IntegerField(blank=True, null=True)),
                ('has_guarantor', models.IntegerField(blank=True, null=True)),
                ('guarantor_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('prepayment', models.BigIntegerField(blank=True, null=True)),
                ('installment_count', models.IntegerField(blank=True, null=True)),
                ('paid_installments', models.IntegerField(blank=True, null=True)),
                ('remaining_debt', models.BigIntegerField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_paid', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('installment', 'پرداخت قسط'), ('partial', 'پرداخت علی\u200cالحساب'), ('full', 'تسویه کامل')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('number_of_installments', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
